import './globals.css'
import React from 'react'
import { Metadata } from 'next'
import localFont from 'next/font/local'
import { ThemesProvider } from '@/components/themes/ThemesProvider'

// cutome font - iran yekan
const yekan = localFont({
  src: './fonts/yekan.woff2',
  display: 'swap',
  variable: '--font-yekan',
})
export const metadata: Metadata = {
  title: 'Crypto',
  description: 'Generated by javad shahrabadi - m.javadshahrabadi@gmail.com',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa">
      <body
        className={`${yekan.className} bg-slate-100 dark:text-white dark:bg-secondary h-[100vh] w-[100vw]`}
      >
        <ThemesProvider attribute="class" enableSystem>
          <main>{children}</main>
        </ThemesProvider>
      </body>
    </html>
  )
}
