import './globals.css'
import React from 'react'
import { Metadata } from 'next'
import localFont from 'next/font/local'

const myFont = localFont({
  src: './fonts/yekan.woff2',
  display: 'swap',
})
export const metadata: Metadata = {
  title: 'Crypto',
  description: 'Generated by javad shahrabadi - m.javadshahrabadi@gmail.com',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={myFont.className}>{children}</body>
    </html>
  )
}
